<?php
$title = 'My solmisation strings';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php
//    echo $this->url('solmik', array('controller' => 'solmik-category', 'action' => 'create')); 
    echo $this->url('solmik-category', array('action' => 'create'));
    ?>">Add new Category</a>
</p>

<table class="table">
    <tr>
        <th>Category</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($categories as $category) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($category->getName()); ?></td>
            <td>
                <a href="<?php echo $this->url('solmik-category', array('action' => 'edit', 'id' => $category->getId()));
        ?>">Edit</a> - 
                <a href="<?php echo $this->url('solmik-category', array('action' => 'delete', 'id' => $category->getId()));
        ?>">Delete</a> - 
                <a href="<?php echo $this->url('solmik-string', array('action' => 'create', 'id' => $category->getId()));
        ?>">Add string</a>
            </td>
        </tr>
        <tr>
            <td>
                <?php $solmistrings = $category->getSolmistrings(); ?> 
                <ul>
                    <?php for ($j = 0; $j < count($solmistrings); $j++) : ?> 
                        <li>
                            <form>
                                <?php echo $solmistrings[$j]->getName() ?>
                                <br>
                                <?php echo $solmistrings[$j]->getBaseScale() ?>, 
                                <input type="text" value="<?php echo $solmistrings[$j]->getString() ?>">
                                <input type="submit" class="go" value="Go">
                            </form>
                            <a href="<?php echo $this->url('solmik-string', array('action' => 'edit', 'id' => $solmistrings[$j]->getId()));?>">Edit string</a>
                        </li>
                    <?php endfor; ?> 
                </ul>
            </td>
        </tr>
    <?php endforeach; ?>
</table>