<?php

$title = 'Delete solmization string';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    " <?php echo $this->escapeHtml($solmistring->getName()); ?> "?
</p>
<?php
$url = $this->url('solmik-string', array(
    'action' => 'delete',
    'id' => $id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>